// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(MatrixSDKFFI)
import MatrixSDKFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ruma_events_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ruma_events_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureRumaEventsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol PrivateStringProtocol: AnyObject, Sendable {
    
}
open class PrivateString: PrivateStringProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_ruma_events_fn_clone_privatestring(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_ruma_events_fn_free_privatestring(handle, $0) }
    }

    

    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrivateString: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = PrivateString

    public static func lift(_ handle: UInt64) throws -> PrivateString {
        return PrivateString(unsafeFromHandle: handle)
    }

    public static func lower(_ value: PrivateString) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrivateString {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: PrivateString, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivateString_lift(_ handle: UInt64) throws -> PrivateString {
    return try FfiConverterTypePrivateString.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivateString_lower(_ value: PrivateString) -> UInt64 {
    return FfiConverterTypePrivateString.lower(value)
}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * The type of `EphemeralRoomEvent` this is.
 *
 * This type can hold an arbitrary string. To build events with a custom type, convert it
 * from a string with `::from()` / `.into()`. To check for events that are not available as a
 * documented variant here, use its string representation, obtained through `.to_string()`.
 */

public enum EphemeralRoomEventType: Equatable, Hashable, CustomStringConvertible {
    
    /**
     * m.receipt
     */
    case receipt
    /**
     * m.typing
     */
    case typing
    /**
     * This variant ensures forward compatibility of the library. It deliberately cannot be
     * used to create custom variants in client code.
     */
    case custom(PrivOwnedStr
    )





// The local Rust `Display` implementation.
public var description: String {
    return try!  FfiConverterString.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_ephemeralroomeventtype_uniffi_trait_display(
            FfiConverterTypeEphemeralRoomEventType_lower(self),$0
    )
}
    )
}
// The local Rust `Eq` implementation - only `eq` is used.
public static func == (self: EphemeralRoomEventType, other: EphemeralRoomEventType) -> Bool {
    return try!  FfiConverterBool.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_ephemeralroomeventtype_uniffi_trait_eq_eq(
            FfiConverterTypeEphemeralRoomEventType_lower(self),
        FfiConverterTypeEphemeralRoomEventType_lower(other),$0
    )
}
    )
}
// The local Rust `Hash` implementation
public func hash(into hasher: inout Hasher) {
    let val = try!  FfiConverterUInt64.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_ephemeralroomeventtype_uniffi_trait_hash(
            FfiConverterTypeEphemeralRoomEventType_lower(self),$0
    )
}
    )
    hasher.combine(val)
}
}

#if compiler(>=6)
extension EphemeralRoomEventType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEphemeralRoomEventType: FfiConverterRustBuffer {
    typealias SwiftType = EphemeralRoomEventType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EphemeralRoomEventType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .receipt
        
        case 2: return .typing
        
        case 3: return .custom(try FfiConverterTypePrivOwnedStr.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EphemeralRoomEventType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .receipt:
            writeInt(&buf, Int32(1))
        
        
        case .typing:
            writeInt(&buf, Int32(2))
        
        
        case let .custom(v1):
            writeInt(&buf, Int32(3))
            FfiConverterTypePrivOwnedStr.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEphemeralRoomEventType_lift(_ buf: RustBuffer) throws -> EphemeralRoomEventType {
    return try FfiConverterTypeEphemeralRoomEventType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEphemeralRoomEventType_lower(_ value: EphemeralRoomEventType) -> RustBuffer {
    return FfiConverterTypeEphemeralRoomEventType.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * The type of `GlobalAccountDataEvent` this is.
 *
 * This type can hold an arbitrary string. To build events with a custom type, convert it
 * from a string with `::from()` / `.into()`. To check for events that are not available as a
 * documented variant here, use its string representation, obtained through `.to_string()`.
 */

public enum GlobalAccountDataEventType: Equatable, Hashable, CustomStringConvertible {
    
    /**
     * m.direct
     */
    case direct
    /**
     * m.identity_server
     */
    case identityServer
    /**
     * m.invite_permission_config
     */
    case invitePermissionConfig
    /**
     * m.ignored_user_list
     */
    case ignoredUserList
    /**
     * m.image_pack.rooms
     */
    case imagePackRooms
    /**
     * m.push_rules
     */
    case pushRules
    /**
     * m.secret_storage.default_key
     */
    case secretStorageDefaultKey
    /**
     * m.secret_storage.key.*
     */
    case secretStorageKey(String
    )
    /**
     * m.media_preview_config
     */
    case mediaPreviewConfig
    /**
     * io.element.msc4278.media_preview_config
     */
    case unstableMediaPreviewConfig
    /**
     * m.recent_emoji
     */
    case recentEmoji
    /**
     * m.key_backup
     */
    case keyBackup
    /**
     * This variant ensures forward compatibility of the library. It deliberately cannot be
     * used to create custom variants in client code.
     */
    case custom(PrivOwnedStr
    )





// The local Rust `Display` implementation.
public var description: String {
    return try!  FfiConverterString.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_globalaccountdataeventtype_uniffi_trait_display(
            FfiConverterTypeGlobalAccountDataEventType_lower(self),$0
    )
}
    )
}
// The local Rust `Eq` implementation - only `eq` is used.
public static func == (self: GlobalAccountDataEventType, other: GlobalAccountDataEventType) -> Bool {
    return try!  FfiConverterBool.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_globalaccountdataeventtype_uniffi_trait_eq_eq(
            FfiConverterTypeGlobalAccountDataEventType_lower(self),
        FfiConverterTypeGlobalAccountDataEventType_lower(other),$0
    )
}
    )
}
// The local Rust `Hash` implementation
public func hash(into hasher: inout Hasher) {
    let val = try!  FfiConverterUInt64.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_globalaccountdataeventtype_uniffi_trait_hash(
            FfiConverterTypeGlobalAccountDataEventType_lower(self),$0
    )
}
    )
    hasher.combine(val)
}
}

#if compiler(>=6)
extension GlobalAccountDataEventType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGlobalAccountDataEventType: FfiConverterRustBuffer {
    typealias SwiftType = GlobalAccountDataEventType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GlobalAccountDataEventType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .direct
        
        case 2: return .identityServer
        
        case 3: return .invitePermissionConfig
        
        case 4: return .ignoredUserList
        
        case 5: return .imagePackRooms
        
        case 6: return .pushRules
        
        case 7: return .secretStorageDefaultKey
        
        case 8: return .secretStorageKey(try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .mediaPreviewConfig
        
        case 10: return .unstableMediaPreviewConfig
        
        case 11: return .recentEmoji
        
        case 12: return .keyBackup
        
        case 13: return .custom(try FfiConverterTypePrivOwnedStr.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: GlobalAccountDataEventType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .direct:
            writeInt(&buf, Int32(1))
        
        
        case .identityServer:
            writeInt(&buf, Int32(2))
        
        
        case .invitePermissionConfig:
            writeInt(&buf, Int32(3))
        
        
        case .ignoredUserList:
            writeInt(&buf, Int32(4))
        
        
        case .imagePackRooms:
            writeInt(&buf, Int32(5))
        
        
        case .pushRules:
            writeInt(&buf, Int32(6))
        
        
        case .secretStorageDefaultKey:
            writeInt(&buf, Int32(7))
        
        
        case let .secretStorageKey(v1):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .mediaPreviewConfig:
            writeInt(&buf, Int32(9))
        
        
        case .unstableMediaPreviewConfig:
            writeInt(&buf, Int32(10))
        
        
        case .recentEmoji:
            writeInt(&buf, Int32(11))
        
        
        case .keyBackup:
            writeInt(&buf, Int32(12))
        
        
        case let .custom(v1):
            writeInt(&buf, Int32(13))
            FfiConverterTypePrivOwnedStr.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGlobalAccountDataEventType_lift(_ buf: RustBuffer) throws -> GlobalAccountDataEventType {
    return try FfiConverterTypeGlobalAccountDataEventType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGlobalAccountDataEventType_lower(_ value: GlobalAccountDataEventType) -> RustBuffer {
    return FfiConverterTypeGlobalAccountDataEventType.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * The type of `MessageLikeEvent` this is.
 *
 * This type can hold an arbitrary string. To build events with a custom type, convert it
 * from a string with `::from()` / `.into()`. To check for events that are not available as a
 * documented variant here, use its string representation, obtained through `.to_string()`.
 */

public enum MessageLikeEventType: Equatable, Hashable, CustomStringConvertible {
    
    /**
     * m.audio
     *
     * This variant uses the unstable type `org.matrix.msc1767.audio`.
     *
     * This variant can also be deserialized from the `m.audio` type.
     */
    case audio
    /**
     * m.call.answer
     */
    case callAnswer
    /**
     * m.call.invite
     */
    case callInvite
    /**
     * m.call.hangup
     */
    case callHangup
    /**
     * m.call.candidates
     */
    case callCandidates
    /**
     * m.call.negotiate
     */
    case callNegotiate
    /**
     * m.call.reject
     */
    case callReject
    /**
     * m.call.sdp_stream_metadata_changed
     *
     * This variant can also be deserialized from the `org.matrix.call.sdp_stream_metadata_changed` type.
     */
    case callSdpStreamMetadataChanged
    /**
     * m.call.select_answer
     */
    case callSelectAnswer
    /**
     * m.emote
     *
     * This variant uses the unstable type `org.matrix.msc1767.emote`.
     *
     * This variant can also be deserialized from the `m.emote` type.
     */
    case emote
    /**
     * m.encrypted
     *
     * This variant uses the unstable type `org.matrix.msc1767.encrypted`.
     *
     * This variant can also be deserialized from the `m.encrypted` type.
     */
    case encrypted
    /**
     * m.file
     *
     * This variant uses the unstable type `org.matrix.msc1767.file`.
     *
     * This variant can also be deserialized from the `m.file` type.
     */
    case file
    /**
     * m.image
     *
     * This variant uses the unstable type `org.matrix.msc1767.image`.
     *
     * This variant can also be deserialized from the `m.image` type.
     */
    case image
    /**
     * m.key.verification.ready
     */
    case keyVerificationReady
    /**
     * m.key.verification.start
     */
    case keyVerificationStart
    /**
     * m.key.verification.cancel
     */
    case keyVerificationCancel
    /**
     * m.key.verification.accept
     */
    case keyVerificationAccept
    /**
     * m.key.verification.key
     */
    case keyVerificationKey
    /**
     * m.key.verification.mac
     */
    case keyVerificationMac
    /**
     * m.key.verification.done
     */
    case keyVerificationDone
    /**
     * m.location
     */
    case location
    /**
     * m.message
     *
     * This variant uses the unstable type `org.matrix.msc1767.message`.
     *
     * This variant can also be deserialized from the `m.message` type.
     */
    case message
    /**
     * m.poll.start
     */
    case pollStart
    /**
     * org.matrix.msc3381.poll.start
     */
    case unstablePollStart
    /**
     * m.poll.response
     */
    case pollResponse
    /**
     * org.matrix.msc3381.poll.response
     */
    case unstablePollResponse
    /**
     * m.poll.end
     */
    case pollEnd
    /**
     * org.matrix.msc3381.poll.end
     */
    case unstablePollEnd
    /**
     * m.beacon
     *
     * This variant uses the unstable type `org.matrix.msc3672.beacon`.
     *
     * This variant can also be deserialized from the `m.beacon` type.
     */
    case beacon
    /**
     * m.reaction
     */
    case reaction
    /**
     * m.room.encrypted
     */
    case roomEncrypted
    /**
     * m.room.message
     */
    case roomMessage
    /**
     * m.room.redaction
     */
    case roomRedaction
    /**
     * m.sticker
     */
    case sticker
    /**
     * m.video
     *
     * This variant uses the unstable type `org.matrix.msc1767.video`.
     *
     * This variant can also be deserialized from the `m.video` type.
     */
    case video
    /**
     * m.voice
     *
     * This variant uses the unstable type `org.matrix.msc3245.voice.v2`.
     *
     * This variant can also be deserialized from the `m.voice` type.
     */
    case voice
    /**
     * m.call.notify
     *
     * This variant uses the unstable type `org.matrix.msc4075.call.notify`.
     *
     * This variant can also be deserialized from the `m.call.notify` type.
     */
    case callNotify
    /**
     * m.rtc.notification
     *
     * This variant uses the unstable type `org.matrix.msc4075.rtc.notification`.
     *
     * This variant can also be deserialized from the `m.rtc.notification` type.
     */
    case rtcNotification
    /**
     * m.rtc.decline
     *
     * This variant uses the unstable type `org.matrix.msc4310.rtc.decline`.
     *
     * This variant can also be deserialized from the `m.rtc.decline` type.
     */
    case rtcDecline
    /**
     * This variant ensures forward compatibility of the library. It deliberately cannot be
     * used to create custom variants in client code.
     */
    case custom(PrivOwnedStr
    )





// The local Rust `Display` implementation.
public var description: String {
    return try!  FfiConverterString.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_messagelikeeventtype_uniffi_trait_display(
            FfiConverterTypeMessageLikeEventType_lower(self),$0
    )
}
    )
}
// The local Rust `Eq` implementation - only `eq` is used.
public static func == (self: MessageLikeEventType, other: MessageLikeEventType) -> Bool {
    return try!  FfiConverterBool.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_messagelikeeventtype_uniffi_trait_eq_eq(
            FfiConverterTypeMessageLikeEventType_lower(self),
        FfiConverterTypeMessageLikeEventType_lower(other),$0
    )
}
    )
}
// The local Rust `Hash` implementation
public func hash(into hasher: inout Hasher) {
    let val = try!  FfiConverterUInt64.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_messagelikeeventtype_uniffi_trait_hash(
            FfiConverterTypeMessageLikeEventType_lower(self),$0
    )
}
    )
    hasher.combine(val)
}
}

#if compiler(>=6)
extension MessageLikeEventType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessageLikeEventType: FfiConverterRustBuffer {
    typealias SwiftType = MessageLikeEventType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MessageLikeEventType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .audio
        
        case 2: return .callAnswer
        
        case 3: return .callInvite
        
        case 4: return .callHangup
        
        case 5: return .callCandidates
        
        case 6: return .callNegotiate
        
        case 7: return .callReject
        
        case 8: return .callSdpStreamMetadataChanged
        
        case 9: return .callSelectAnswer
        
        case 10: return .emote
        
        case 11: return .encrypted
        
        case 12: return .file
        
        case 13: return .image
        
        case 14: return .keyVerificationReady
        
        case 15: return .keyVerificationStart
        
        case 16: return .keyVerificationCancel
        
        case 17: return .keyVerificationAccept
        
        case 18: return .keyVerificationKey
        
        case 19: return .keyVerificationMac
        
        case 20: return .keyVerificationDone
        
        case 21: return .location
        
        case 22: return .message
        
        case 23: return .pollStart
        
        case 24: return .unstablePollStart
        
        case 25: return .pollResponse
        
        case 26: return .unstablePollResponse
        
        case 27: return .pollEnd
        
        case 28: return .unstablePollEnd
        
        case 29: return .beacon
        
        case 30: return .reaction
        
        case 31: return .roomEncrypted
        
        case 32: return .roomMessage
        
        case 33: return .roomRedaction
        
        case 34: return .sticker
        
        case 35: return .video
        
        case 36: return .voice
        
        case 37: return .callNotify
        
        case 38: return .rtcNotification
        
        case 39: return .rtcDecline
        
        case 40: return .custom(try FfiConverterTypePrivOwnedStr.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MessageLikeEventType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .audio:
            writeInt(&buf, Int32(1))
        
        
        case .callAnswer:
            writeInt(&buf, Int32(2))
        
        
        case .callInvite:
            writeInt(&buf, Int32(3))
        
        
        case .callHangup:
            writeInt(&buf, Int32(4))
        
        
        case .callCandidates:
            writeInt(&buf, Int32(5))
        
        
        case .callNegotiate:
            writeInt(&buf, Int32(6))
        
        
        case .callReject:
            writeInt(&buf, Int32(7))
        
        
        case .callSdpStreamMetadataChanged:
            writeInt(&buf, Int32(8))
        
        
        case .callSelectAnswer:
            writeInt(&buf, Int32(9))
        
        
        case .emote:
            writeInt(&buf, Int32(10))
        
        
        case .encrypted:
            writeInt(&buf, Int32(11))
        
        
        case .file:
            writeInt(&buf, Int32(12))
        
        
        case .image:
            writeInt(&buf, Int32(13))
        
        
        case .keyVerificationReady:
            writeInt(&buf, Int32(14))
        
        
        case .keyVerificationStart:
            writeInt(&buf, Int32(15))
        
        
        case .keyVerificationCancel:
            writeInt(&buf, Int32(16))
        
        
        case .keyVerificationAccept:
            writeInt(&buf, Int32(17))
        
        
        case .keyVerificationKey:
            writeInt(&buf, Int32(18))
        
        
        case .keyVerificationMac:
            writeInt(&buf, Int32(19))
        
        
        case .keyVerificationDone:
            writeInt(&buf, Int32(20))
        
        
        case .location:
            writeInt(&buf, Int32(21))
        
        
        case .message:
            writeInt(&buf, Int32(22))
        
        
        case .pollStart:
            writeInt(&buf, Int32(23))
        
        
        case .unstablePollStart:
            writeInt(&buf, Int32(24))
        
        
        case .pollResponse:
            writeInt(&buf, Int32(25))
        
        
        case .unstablePollResponse:
            writeInt(&buf, Int32(26))
        
        
        case .pollEnd:
            writeInt(&buf, Int32(27))
        
        
        case .unstablePollEnd:
            writeInt(&buf, Int32(28))
        
        
        case .beacon:
            writeInt(&buf, Int32(29))
        
        
        case .reaction:
            writeInt(&buf, Int32(30))
        
        
        case .roomEncrypted:
            writeInt(&buf, Int32(31))
        
        
        case .roomMessage:
            writeInt(&buf, Int32(32))
        
        
        case .roomRedaction:
            writeInt(&buf, Int32(33))
        
        
        case .sticker:
            writeInt(&buf, Int32(34))
        
        
        case .video:
            writeInt(&buf, Int32(35))
        
        
        case .voice:
            writeInt(&buf, Int32(36))
        
        
        case .callNotify:
            writeInt(&buf, Int32(37))
        
        
        case .rtcNotification:
            writeInt(&buf, Int32(38))
        
        
        case .rtcDecline:
            writeInt(&buf, Int32(39))
        
        
        case let .custom(v1):
            writeInt(&buf, Int32(40))
            FfiConverterTypePrivOwnedStr.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageLikeEventType_lift(_ buf: RustBuffer) throws -> MessageLikeEventType {
    return try FfiConverterTypeMessageLikeEventType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageLikeEventType_lower(_ value: MessageLikeEventType) -> RustBuffer {
    return FfiConverterTypeMessageLikeEventType.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * The type of `RoomAccountDataEvent` this is.
 *
 * This type can hold an arbitrary string. To build events with a custom type, convert it
 * from a string with `::from()` / `.into()`. To check for events that are not available as a
 * documented variant here, use its string representation, obtained through `.to_string()`.
 */

public enum RoomAccountDataEventType: Equatable, Hashable, CustomStringConvertible {
    
    /**
     * m.fully_read
     */
    case fullyRead
    /**
     * m.tag
     */
    case tag
    /**
     * m.marked_unread
     */
    case markedUnread
    /**
     * com.famedly.marked_unread
     */
    case unstableMarkedUnread
    /**
     * m.media_preview_config
     */
    case mediaPreviewConfig
    /**
     * io.element.msc4278.media_preview_config
     */
    case unstableMediaPreviewConfig
    /**
     * m.space_order
     *
     * This variant uses the unstable type `org.matrix.msc3230.space_order`.
     *
     * This variant can also be deserialized from the `m.space_order` type.
     */
    case spaceOrder
    /**
     * This variant ensures forward compatibility of the library. It deliberately cannot be
     * used to create custom variants in client code.
     */
    case custom(PrivOwnedStr
    )





// The local Rust `Display` implementation.
public var description: String {
    return try!  FfiConverterString.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_roomaccountdataeventtype_uniffi_trait_display(
            FfiConverterTypeRoomAccountDataEventType_lower(self),$0
    )
}
    )
}
// The local Rust `Eq` implementation - only `eq` is used.
public static func == (self: RoomAccountDataEventType, other: RoomAccountDataEventType) -> Bool {
    return try!  FfiConverterBool.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_roomaccountdataeventtype_uniffi_trait_eq_eq(
            FfiConverterTypeRoomAccountDataEventType_lower(self),
        FfiConverterTypeRoomAccountDataEventType_lower(other),$0
    )
}
    )
}
// The local Rust `Hash` implementation
public func hash(into hasher: inout Hasher) {
    let val = try!  FfiConverterUInt64.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_roomaccountdataeventtype_uniffi_trait_hash(
            FfiConverterTypeRoomAccountDataEventType_lower(self),$0
    )
}
    )
    hasher.combine(val)
}
}

#if compiler(>=6)
extension RoomAccountDataEventType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRoomAccountDataEventType: FfiConverterRustBuffer {
    typealias SwiftType = RoomAccountDataEventType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RoomAccountDataEventType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .fullyRead
        
        case 2: return .tag
        
        case 3: return .markedUnread
        
        case 4: return .unstableMarkedUnread
        
        case 5: return .mediaPreviewConfig
        
        case 6: return .unstableMediaPreviewConfig
        
        case 7: return .spaceOrder
        
        case 8: return .custom(try FfiConverterTypePrivOwnedStr.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RoomAccountDataEventType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .fullyRead:
            writeInt(&buf, Int32(1))
        
        
        case .tag:
            writeInt(&buf, Int32(2))
        
        
        case .markedUnread:
            writeInt(&buf, Int32(3))
        
        
        case .unstableMarkedUnread:
            writeInt(&buf, Int32(4))
        
        
        case .mediaPreviewConfig:
            writeInt(&buf, Int32(5))
        
        
        case .unstableMediaPreviewConfig:
            writeInt(&buf, Int32(6))
        
        
        case .spaceOrder:
            writeInt(&buf, Int32(7))
        
        
        case let .custom(v1):
            writeInt(&buf, Int32(8))
            FfiConverterTypePrivOwnedStr.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRoomAccountDataEventType_lift(_ buf: RustBuffer) throws -> RoomAccountDataEventType {
    return try FfiConverterTypeRoomAccountDataEventType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRoomAccountDataEventType_lower(_ value: RoomAccountDataEventType) -> RustBuffer {
    return FfiConverterTypeRoomAccountDataEventType.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * The type of `StateEvent` this is.
 *
 * This type can hold an arbitrary string. To build events with a custom type, convert it
 * from a string with `::from()` / `.into()`. To check for events that are not available as a
 * documented variant here, use its string representation, obtained through `.to_string()`.
 */

public enum StateEventType: Equatable, Hashable, CustomStringConvertible {
    
    /**
     * m.policy.rule.room
     */
    case policyRuleRoom
    /**
     * m.policy.rule.server
     */
    case policyRuleServer
    /**
     * m.policy.rule.user
     */
    case policyRuleUser
    /**
     * m.room.avatar
     */
    case roomAvatar
    /**
     * m.room.canonical_alias
     */
    case roomCanonicalAlias
    /**
     * m.room.create
     */
    case roomCreate
    /**
     * m.room.encryption
     */
    case roomEncryption
    /**
     * m.room.guest_access
     */
    case roomGuestAccess
    /**
     * m.room.history_visibility
     */
    case roomHistoryVisibility
    /**
     * m.room.image_pack
     */
    case roomImagePack
    /**
     * m.room.join_rules
     */
    case roomJoinRules
    /**
     * m.room.language
     *
     * This variant uses the unstable type `org.matrix.msc4334.room.language`.
     *
     * This variant can also be deserialized from the `m.room.language` type.
     */
    case roomLanguage
    /**
     * m.room.member
     */
    case roomMember
    /**
     * m.room.name
     */
    case roomName
    /**
     * m.room.pinned_events
     */
    case roomPinnedEvents
    /**
     * m.room.policy
     */
    case roomPolicy
    /**
     * m.room.power_levels
     */
    case roomPowerLevels
    /**
     * m.room.server_acl
     */
    case roomServerAcl
    /**
     * m.room.third_party_invite
     */
    case roomThirdPartyInvite
    /**
     * m.room.tombstone
     */
    case roomTombstone
    /**
     * m.room.topic
     */
    case roomTopic
    /**
     * m.space.child
     */
    case spaceChild
    /**
     * m.space.parent
     */
    case spaceParent
    /**
     * m.beacon_info
     *
     * This variant uses the unstable type `org.matrix.msc3672.beacon_info`.
     *
     * This variant can also be deserialized from the `m.beacon_info` type.
     */
    case beaconInfo
    /**
     * m.call.member
     *
     * This variant uses the unstable type `org.matrix.msc3401.call.member`.
     *
     * This variant can also be deserialized from the `m.call.member` type.
     */
    case callMember
    /**
     * m.member_hints
     *
     * This variant uses the unstable type `io.element.functional_members`.
     *
     * This variant can also be deserialized from the `m.member_hints` type.
     */
    case memberHints
    /**
     * This variant ensures forward compatibility of the library. It deliberately cannot be
     * used to create custom variants in client code.
     */
    case custom(PrivOwnedStr
    )





// The local Rust `Display` implementation.
public var description: String {
    return try!  FfiConverterString.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_stateeventtype_uniffi_trait_display(
            FfiConverterTypeStateEventType_lower(self),$0
    )
}
    )
}
// The local Rust `Eq` implementation - only `eq` is used.
public static func == (self: StateEventType, other: StateEventType) -> Bool {
    return try!  FfiConverterBool.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_stateeventtype_uniffi_trait_eq_eq(
            FfiConverterTypeStateEventType_lower(self),
        FfiConverterTypeStateEventType_lower(other),$0
    )
}
    )
}
// The local Rust `Hash` implementation
public func hash(into hasher: inout Hasher) {
    let val = try!  FfiConverterUInt64.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_stateeventtype_uniffi_trait_hash(
            FfiConverterTypeStateEventType_lower(self),$0
    )
}
    )
    hasher.combine(val)
}
}

#if compiler(>=6)
extension StateEventType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStateEventType: FfiConverterRustBuffer {
    typealias SwiftType = StateEventType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StateEventType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .policyRuleRoom
        
        case 2: return .policyRuleServer
        
        case 3: return .policyRuleUser
        
        case 4: return .roomAvatar
        
        case 5: return .roomCanonicalAlias
        
        case 6: return .roomCreate
        
        case 7: return .roomEncryption
        
        case 8: return .roomGuestAccess
        
        case 9: return .roomHistoryVisibility
        
        case 10: return .roomImagePack
        
        case 11: return .roomJoinRules
        
        case 12: return .roomLanguage
        
        case 13: return .roomMember
        
        case 14: return .roomName
        
        case 15: return .roomPinnedEvents
        
        case 16: return .roomPolicy
        
        case 17: return .roomPowerLevels
        
        case 18: return .roomServerAcl
        
        case 19: return .roomThirdPartyInvite
        
        case 20: return .roomTombstone
        
        case 21: return .roomTopic
        
        case 22: return .spaceChild
        
        case 23: return .spaceParent
        
        case 24: return .beaconInfo
        
        case 25: return .callMember
        
        case 26: return .memberHints
        
        case 27: return .custom(try FfiConverterTypePrivOwnedStr.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StateEventType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .policyRuleRoom:
            writeInt(&buf, Int32(1))
        
        
        case .policyRuleServer:
            writeInt(&buf, Int32(2))
        
        
        case .policyRuleUser:
            writeInt(&buf, Int32(3))
        
        
        case .roomAvatar:
            writeInt(&buf, Int32(4))
        
        
        case .roomCanonicalAlias:
            writeInt(&buf, Int32(5))
        
        
        case .roomCreate:
            writeInt(&buf, Int32(6))
        
        
        case .roomEncryption:
            writeInt(&buf, Int32(7))
        
        
        case .roomGuestAccess:
            writeInt(&buf, Int32(8))
        
        
        case .roomHistoryVisibility:
            writeInt(&buf, Int32(9))
        
        
        case .roomImagePack:
            writeInt(&buf, Int32(10))
        
        
        case .roomJoinRules:
            writeInt(&buf, Int32(11))
        
        
        case .roomLanguage:
            writeInt(&buf, Int32(12))
        
        
        case .roomMember:
            writeInt(&buf, Int32(13))
        
        
        case .roomName:
            writeInt(&buf, Int32(14))
        
        
        case .roomPinnedEvents:
            writeInt(&buf, Int32(15))
        
        
        case .roomPolicy:
            writeInt(&buf, Int32(16))
        
        
        case .roomPowerLevels:
            writeInt(&buf, Int32(17))
        
        
        case .roomServerAcl:
            writeInt(&buf, Int32(18))
        
        
        case .roomThirdPartyInvite:
            writeInt(&buf, Int32(19))
        
        
        case .roomTombstone:
            writeInt(&buf, Int32(20))
        
        
        case .roomTopic:
            writeInt(&buf, Int32(21))
        
        
        case .spaceChild:
            writeInt(&buf, Int32(22))
        
        
        case .spaceParent:
            writeInt(&buf, Int32(23))
        
        
        case .beaconInfo:
            writeInt(&buf, Int32(24))
        
        
        case .callMember:
            writeInt(&buf, Int32(25))
        
        
        case .memberHints:
            writeInt(&buf, Int32(26))
        
        
        case let .custom(v1):
            writeInt(&buf, Int32(27))
            FfiConverterTypePrivOwnedStr.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStateEventType_lift(_ buf: RustBuffer) throws -> StateEventType {
    return try FfiConverterTypeStateEventType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStateEventType_lower(_ value: StateEventType) -> RustBuffer {
    return FfiConverterTypeStateEventType.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * The type of `TimelineEvent` this is.
 *
 * This type can hold an arbitrary string. To build events with a custom type, convert it
 * from a string with `::from()` / `.into()`. To check for events that are not available as a
 * documented variant here, use its string representation, obtained through `.to_string()`.
 */

public enum TimelineEventType: Equatable, Hashable, CustomStringConvertible {
    
    /**
     * m.audio
     *
     * This variant uses the unstable type `org.matrix.msc1767.audio`.
     *
     * This variant can also be deserialized from the `m.audio` type.
     */
    case audio
    /**
     * m.call.answer
     */
    case callAnswer
    /**
     * m.call.invite
     */
    case callInvite
    /**
     * m.call.hangup
     */
    case callHangup
    /**
     * m.call.candidates
     */
    case callCandidates
    /**
     * m.call.negotiate
     */
    case callNegotiate
    /**
     * m.call.reject
     */
    case callReject
    /**
     * m.call.sdp_stream_metadata_changed
     *
     * This variant can also be deserialized from the `org.matrix.call.sdp_stream_metadata_changed` type.
     */
    case callSdpStreamMetadataChanged
    /**
     * m.call.select_answer
     */
    case callSelectAnswer
    /**
     * m.emote
     *
     * This variant uses the unstable type `org.matrix.msc1767.emote`.
     *
     * This variant can also be deserialized from the `m.emote` type.
     */
    case emote
    /**
     * m.encrypted
     *
     * This variant uses the unstable type `org.matrix.msc1767.encrypted`.
     *
     * This variant can also be deserialized from the `m.encrypted` type.
     */
    case encrypted
    /**
     * m.file
     *
     * This variant uses the unstable type `org.matrix.msc1767.file`.
     *
     * This variant can also be deserialized from the `m.file` type.
     */
    case file
    /**
     * m.image
     *
     * This variant uses the unstable type `org.matrix.msc1767.image`.
     *
     * This variant can also be deserialized from the `m.image` type.
     */
    case image
    /**
     * m.key.verification.ready
     */
    case keyVerificationReady
    /**
     * m.key.verification.start
     */
    case keyVerificationStart
    /**
     * m.key.verification.cancel
     */
    case keyVerificationCancel
    /**
     * m.key.verification.accept
     */
    case keyVerificationAccept
    /**
     * m.key.verification.key
     */
    case keyVerificationKey
    /**
     * m.key.verification.mac
     */
    case keyVerificationMac
    /**
     * m.key.verification.done
     */
    case keyVerificationDone
    /**
     * m.location
     */
    case location
    /**
     * m.message
     *
     * This variant uses the unstable type `org.matrix.msc1767.message`.
     *
     * This variant can also be deserialized from the `m.message` type.
     */
    case message
    /**
     * m.poll.start
     */
    case pollStart
    /**
     * org.matrix.msc3381.poll.start
     */
    case unstablePollStart
    /**
     * m.poll.response
     */
    case pollResponse
    /**
     * org.matrix.msc3381.poll.response
     */
    case unstablePollResponse
    /**
     * m.poll.end
     */
    case pollEnd
    /**
     * org.matrix.msc3381.poll.end
     */
    case unstablePollEnd
    /**
     * m.beacon
     *
     * This variant uses the unstable type `org.matrix.msc3672.beacon`.
     *
     * This variant can also be deserialized from the `m.beacon` type.
     */
    case beacon
    /**
     * m.reaction
     */
    case reaction
    /**
     * m.room.encrypted
     */
    case roomEncrypted
    /**
     * m.room.message
     */
    case roomMessage
    /**
     * m.room.redaction
     */
    case roomRedaction
    /**
     * m.sticker
     */
    case sticker
    /**
     * m.video
     *
     * This variant uses the unstable type `org.matrix.msc1767.video`.
     *
     * This variant can also be deserialized from the `m.video` type.
     */
    case video
    /**
     * m.voice
     *
     * This variant uses the unstable type `org.matrix.msc3245.voice.v2`.
     *
     * This variant can also be deserialized from the `m.voice` type.
     */
    case voice
    /**
     * m.call.notify
     *
     * This variant uses the unstable type `org.matrix.msc4075.call.notify`.
     *
     * This variant can also be deserialized from the `m.call.notify` type.
     */
    case callNotify
    /**
     * m.rtc.notification
     *
     * This variant uses the unstable type `org.matrix.msc4075.rtc.notification`.
     *
     * This variant can also be deserialized from the `m.rtc.notification` type.
     */
    case rtcNotification
    /**
     * m.rtc.decline
     *
     * This variant uses the unstable type `org.matrix.msc4310.rtc.decline`.
     *
     * This variant can also be deserialized from the `m.rtc.decline` type.
     */
    case rtcDecline
    /**
     * m.policy.rule.room
     */
    case policyRuleRoom
    /**
     * m.policy.rule.server
     */
    case policyRuleServer
    /**
     * m.policy.rule.user
     */
    case policyRuleUser
    /**
     * m.room.avatar
     */
    case roomAvatar
    /**
     * m.room.canonical_alias
     */
    case roomCanonicalAlias
    /**
     * m.room.create
     */
    case roomCreate
    /**
     * m.room.encryption
     */
    case roomEncryption
    /**
     * m.room.guest_access
     */
    case roomGuestAccess
    /**
     * m.room.history_visibility
     */
    case roomHistoryVisibility
    /**
     * m.room.image_pack
     */
    case roomImagePack
    /**
     * m.room.join_rules
     */
    case roomJoinRules
    /**
     * m.room.language
     *
     * This variant uses the unstable type `org.matrix.msc4334.room.language`.
     *
     * This variant can also be deserialized from the `m.room.language` type.
     */
    case roomLanguage
    /**
     * m.room.member
     */
    case roomMember
    /**
     * m.room.name
     */
    case roomName
    /**
     * m.room.pinned_events
     */
    case roomPinnedEvents
    /**
     * m.room.policy
     */
    case roomPolicy
    /**
     * m.room.power_levels
     */
    case roomPowerLevels
    /**
     * m.room.server_acl
     */
    case roomServerAcl
    /**
     * m.room.third_party_invite
     */
    case roomThirdPartyInvite
    /**
     * m.room.tombstone
     */
    case roomTombstone
    /**
     * m.room.topic
     */
    case roomTopic
    /**
     * m.space.child
     */
    case spaceChild
    /**
     * m.space.parent
     */
    case spaceParent
    /**
     * m.beacon_info
     *
     * This variant uses the unstable type `org.matrix.msc3672.beacon_info`.
     *
     * This variant can also be deserialized from the `m.beacon_info` type.
     */
    case beaconInfo
    /**
     * m.call.member
     *
     * This variant uses the unstable type `org.matrix.msc3401.call.member`.
     *
     * This variant can also be deserialized from the `m.call.member` type.
     */
    case callMember
    /**
     * m.member_hints
     *
     * This variant uses the unstable type `io.element.functional_members`.
     *
     * This variant can also be deserialized from the `m.member_hints` type.
     */
    case memberHints
    /**
     * This variant ensures forward compatibility of the library. It deliberately cannot be
     * used to create custom variants in client code.
     */
    case custom(PrivOwnedStr
    )





// The local Rust `Display` implementation.
public var description: String {
    return try!  FfiConverterString.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_timelineeventtype_uniffi_trait_display(
            FfiConverterTypeTimelineEventType_lower(self),$0
    )
}
    )
}
// The local Rust `Eq` implementation - only `eq` is used.
public static func == (self: TimelineEventType, other: TimelineEventType) -> Bool {
    return try!  FfiConverterBool.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_timelineeventtype_uniffi_trait_eq_eq(
            FfiConverterTypeTimelineEventType_lower(self),
        FfiConverterTypeTimelineEventType_lower(other),$0
    )
}
    )
}
// The local Rust `Hash` implementation
public func hash(into hasher: inout Hasher) {
    let val = try!  FfiConverterUInt64.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_timelineeventtype_uniffi_trait_hash(
            FfiConverterTypeTimelineEventType_lower(self),$0
    )
}
    )
    hasher.combine(val)
}
}

#if compiler(>=6)
extension TimelineEventType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTimelineEventType: FfiConverterRustBuffer {
    typealias SwiftType = TimelineEventType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TimelineEventType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .audio
        
        case 2: return .callAnswer
        
        case 3: return .callInvite
        
        case 4: return .callHangup
        
        case 5: return .callCandidates
        
        case 6: return .callNegotiate
        
        case 7: return .callReject
        
        case 8: return .callSdpStreamMetadataChanged
        
        case 9: return .callSelectAnswer
        
        case 10: return .emote
        
        case 11: return .encrypted
        
        case 12: return .file
        
        case 13: return .image
        
        case 14: return .keyVerificationReady
        
        case 15: return .keyVerificationStart
        
        case 16: return .keyVerificationCancel
        
        case 17: return .keyVerificationAccept
        
        case 18: return .keyVerificationKey
        
        case 19: return .keyVerificationMac
        
        case 20: return .keyVerificationDone
        
        case 21: return .location
        
        case 22: return .message
        
        case 23: return .pollStart
        
        case 24: return .unstablePollStart
        
        case 25: return .pollResponse
        
        case 26: return .unstablePollResponse
        
        case 27: return .pollEnd
        
        case 28: return .unstablePollEnd
        
        case 29: return .beacon
        
        case 30: return .reaction
        
        case 31: return .roomEncrypted
        
        case 32: return .roomMessage
        
        case 33: return .roomRedaction
        
        case 34: return .sticker
        
        case 35: return .video
        
        case 36: return .voice
        
        case 37: return .callNotify
        
        case 38: return .rtcNotification
        
        case 39: return .rtcDecline
        
        case 40: return .policyRuleRoom
        
        case 41: return .policyRuleServer
        
        case 42: return .policyRuleUser
        
        case 43: return .roomAvatar
        
        case 44: return .roomCanonicalAlias
        
        case 45: return .roomCreate
        
        case 46: return .roomEncryption
        
        case 47: return .roomGuestAccess
        
        case 48: return .roomHistoryVisibility
        
        case 49: return .roomImagePack
        
        case 50: return .roomJoinRules
        
        case 51: return .roomLanguage
        
        case 52: return .roomMember
        
        case 53: return .roomName
        
        case 54: return .roomPinnedEvents
        
        case 55: return .roomPolicy
        
        case 56: return .roomPowerLevels
        
        case 57: return .roomServerAcl
        
        case 58: return .roomThirdPartyInvite
        
        case 59: return .roomTombstone
        
        case 60: return .roomTopic
        
        case 61: return .spaceChild
        
        case 62: return .spaceParent
        
        case 63: return .beaconInfo
        
        case 64: return .callMember
        
        case 65: return .memberHints
        
        case 66: return .custom(try FfiConverterTypePrivOwnedStr.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TimelineEventType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .audio:
            writeInt(&buf, Int32(1))
        
        
        case .callAnswer:
            writeInt(&buf, Int32(2))
        
        
        case .callInvite:
            writeInt(&buf, Int32(3))
        
        
        case .callHangup:
            writeInt(&buf, Int32(4))
        
        
        case .callCandidates:
            writeInt(&buf, Int32(5))
        
        
        case .callNegotiate:
            writeInt(&buf, Int32(6))
        
        
        case .callReject:
            writeInt(&buf, Int32(7))
        
        
        case .callSdpStreamMetadataChanged:
            writeInt(&buf, Int32(8))
        
        
        case .callSelectAnswer:
            writeInt(&buf, Int32(9))
        
        
        case .emote:
            writeInt(&buf, Int32(10))
        
        
        case .encrypted:
            writeInt(&buf, Int32(11))
        
        
        case .file:
            writeInt(&buf, Int32(12))
        
        
        case .image:
            writeInt(&buf, Int32(13))
        
        
        case .keyVerificationReady:
            writeInt(&buf, Int32(14))
        
        
        case .keyVerificationStart:
            writeInt(&buf, Int32(15))
        
        
        case .keyVerificationCancel:
            writeInt(&buf, Int32(16))
        
        
        case .keyVerificationAccept:
            writeInt(&buf, Int32(17))
        
        
        case .keyVerificationKey:
            writeInt(&buf, Int32(18))
        
        
        case .keyVerificationMac:
            writeInt(&buf, Int32(19))
        
        
        case .keyVerificationDone:
            writeInt(&buf, Int32(20))
        
        
        case .location:
            writeInt(&buf, Int32(21))
        
        
        case .message:
            writeInt(&buf, Int32(22))
        
        
        case .pollStart:
            writeInt(&buf, Int32(23))
        
        
        case .unstablePollStart:
            writeInt(&buf, Int32(24))
        
        
        case .pollResponse:
            writeInt(&buf, Int32(25))
        
        
        case .unstablePollResponse:
            writeInt(&buf, Int32(26))
        
        
        case .pollEnd:
            writeInt(&buf, Int32(27))
        
        
        case .unstablePollEnd:
            writeInt(&buf, Int32(28))
        
        
        case .beacon:
            writeInt(&buf, Int32(29))
        
        
        case .reaction:
            writeInt(&buf, Int32(30))
        
        
        case .roomEncrypted:
            writeInt(&buf, Int32(31))
        
        
        case .roomMessage:
            writeInt(&buf, Int32(32))
        
        
        case .roomRedaction:
            writeInt(&buf, Int32(33))
        
        
        case .sticker:
            writeInt(&buf, Int32(34))
        
        
        case .video:
            writeInt(&buf, Int32(35))
        
        
        case .voice:
            writeInt(&buf, Int32(36))
        
        
        case .callNotify:
            writeInt(&buf, Int32(37))
        
        
        case .rtcNotification:
            writeInt(&buf, Int32(38))
        
        
        case .rtcDecline:
            writeInt(&buf, Int32(39))
        
        
        case .policyRuleRoom:
            writeInt(&buf, Int32(40))
        
        
        case .policyRuleServer:
            writeInt(&buf, Int32(41))
        
        
        case .policyRuleUser:
            writeInt(&buf, Int32(42))
        
        
        case .roomAvatar:
            writeInt(&buf, Int32(43))
        
        
        case .roomCanonicalAlias:
            writeInt(&buf, Int32(44))
        
        
        case .roomCreate:
            writeInt(&buf, Int32(45))
        
        
        case .roomEncryption:
            writeInt(&buf, Int32(46))
        
        
        case .roomGuestAccess:
            writeInt(&buf, Int32(47))
        
        
        case .roomHistoryVisibility:
            writeInt(&buf, Int32(48))
        
        
        case .roomImagePack:
            writeInt(&buf, Int32(49))
        
        
        case .roomJoinRules:
            writeInt(&buf, Int32(50))
        
        
        case .roomLanguage:
            writeInt(&buf, Int32(51))
        
        
        case .roomMember:
            writeInt(&buf, Int32(52))
        
        
        case .roomName:
            writeInt(&buf, Int32(53))
        
        
        case .roomPinnedEvents:
            writeInt(&buf, Int32(54))
        
        
        case .roomPolicy:
            writeInt(&buf, Int32(55))
        
        
        case .roomPowerLevels:
            writeInt(&buf, Int32(56))
        
        
        case .roomServerAcl:
            writeInt(&buf, Int32(57))
        
        
        case .roomThirdPartyInvite:
            writeInt(&buf, Int32(58))
        
        
        case .roomTombstone:
            writeInt(&buf, Int32(59))
        
        
        case .roomTopic:
            writeInt(&buf, Int32(60))
        
        
        case .spaceChild:
            writeInt(&buf, Int32(61))
        
        
        case .spaceParent:
            writeInt(&buf, Int32(62))
        
        
        case .beaconInfo:
            writeInt(&buf, Int32(63))
        
        
        case .callMember:
            writeInt(&buf, Int32(64))
        
        
        case .memberHints:
            writeInt(&buf, Int32(65))
        
        
        case let .custom(v1):
            writeInt(&buf, Int32(66))
            FfiConverterTypePrivOwnedStr.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimelineEventType_lift(_ buf: RustBuffer) throws -> TimelineEventType {
    return try FfiConverterTypeTimelineEventType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimelineEventType_lower(_ value: TimelineEventType) -> RustBuffer {
    return FfiConverterTypeTimelineEventType.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * The type of `ToDeviceEvent` this is.
 *
 * This type can hold an arbitrary string. To build events with a custom type, convert it
 * from a string with `::from()` / `.into()`. To check for events that are not available as a
 * documented variant here, use its string representation, obtained through `.to_string()`.
 */

public enum ToDeviceEventType: Equatable, Hashable, CustomStringConvertible {
    
    /**
     * m.dummy
     */
    case dummy
    /**
     * m.room_key
     */
    case roomKey
    /**
     * m.room_key_request
     */
    case roomKeyRequest
    /**
     * m.room_key.withheld
     */
    case roomKeyWithheld
    /**
     * m.forwarded_room_key
     */
    case forwardedRoomKey
    /**
     * m.key.verification.request
     */
    case keyVerificationRequest
    /**
     * m.key.verification.ready
     */
    case keyVerificationReady
    /**
     * m.key.verification.start
     */
    case keyVerificationStart
    /**
     * m.key.verification.cancel
     */
    case keyVerificationCancel
    /**
     * m.key.verification.accept
     */
    case keyVerificationAccept
    /**
     * m.key.verification.key
     */
    case keyVerificationKey
    /**
     * m.key.verification.mac
     */
    case keyVerificationMac
    /**
     * m.key.verification.done
     */
    case keyVerificationDone
    /**
     * m.room.encrypted
     */
    case roomEncrypted
    /**
     * m.secret.request
     */
    case secretRequest
    /**
     * m.secret.send
     */
    case secretSend
    /**
     * m.secret.push
     *
     * This variant uses the unstable type `io.element.msc4385.secret.push`.
     *
     * This variant can also be deserialized from the `m.secret.push` type.
     */
    case secretPush
    /**
     * This variant ensures forward compatibility of the library. It deliberately cannot be
     * used to create custom variants in client code.
     */
    case custom(PrivOwnedStr
    )





// The local Rust `Display` implementation.
public var description: String {
    return try!  FfiConverterString.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_todeviceeventtype_uniffi_trait_display(
            FfiConverterTypeToDeviceEventType_lower(self),$0
    )
}
    )
}
// The local Rust `Eq` implementation - only `eq` is used.
public static func == (self: ToDeviceEventType, other: ToDeviceEventType) -> Bool {
    return try!  FfiConverterBool.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_todeviceeventtype_uniffi_trait_eq_eq(
            FfiConverterTypeToDeviceEventType_lower(self),
        FfiConverterTypeToDeviceEventType_lower(other),$0
    )
}
    )
}
// The local Rust `Hash` implementation
public func hash(into hasher: inout Hasher) {
    let val = try!  FfiConverterUInt64.lift(
        try! rustCall() {
    uniffi_ruma_events_fn_method_todeviceeventtype_uniffi_trait_hash(
            FfiConverterTypeToDeviceEventType_lower(self),$0
    )
}
    )
    hasher.combine(val)
}
}

#if compiler(>=6)
extension ToDeviceEventType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeToDeviceEventType: FfiConverterRustBuffer {
    typealias SwiftType = ToDeviceEventType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ToDeviceEventType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .dummy
        
        case 2: return .roomKey
        
        case 3: return .roomKeyRequest
        
        case 4: return .roomKeyWithheld
        
        case 5: return .forwardedRoomKey
        
        case 6: return .keyVerificationRequest
        
        case 7: return .keyVerificationReady
        
        case 8: return .keyVerificationStart
        
        case 9: return .keyVerificationCancel
        
        case 10: return .keyVerificationAccept
        
        case 11: return .keyVerificationKey
        
        case 12: return .keyVerificationMac
        
        case 13: return .keyVerificationDone
        
        case 14: return .roomEncrypted
        
        case 15: return .secretRequest
        
        case 16: return .secretSend
        
        case 17: return .secretPush
        
        case 18: return .custom(try FfiConverterTypePrivOwnedStr.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ToDeviceEventType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .dummy:
            writeInt(&buf, Int32(1))
        
        
        case .roomKey:
            writeInt(&buf, Int32(2))
        
        
        case .roomKeyRequest:
            writeInt(&buf, Int32(3))
        
        
        case .roomKeyWithheld:
            writeInt(&buf, Int32(4))
        
        
        case .forwardedRoomKey:
            writeInt(&buf, Int32(5))
        
        
        case .keyVerificationRequest:
            writeInt(&buf, Int32(6))
        
        
        case .keyVerificationReady:
            writeInt(&buf, Int32(7))
        
        
        case .keyVerificationStart:
            writeInt(&buf, Int32(8))
        
        
        case .keyVerificationCancel:
            writeInt(&buf, Int32(9))
        
        
        case .keyVerificationAccept:
            writeInt(&buf, Int32(10))
        
        
        case .keyVerificationKey:
            writeInt(&buf, Int32(11))
        
        
        case .keyVerificationMac:
            writeInt(&buf, Int32(12))
        
        
        case .keyVerificationDone:
            writeInt(&buf, Int32(13))
        
        
        case .roomEncrypted:
            writeInt(&buf, Int32(14))
        
        
        case .secretRequest:
            writeInt(&buf, Int32(15))
        
        
        case .secretSend:
            writeInt(&buf, Int32(16))
        
        
        case .secretPush:
            writeInt(&buf, Int32(17))
        
        
        case let .custom(v1):
            writeInt(&buf, Int32(18))
            FfiConverterTypePrivOwnedStr.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeToDeviceEventType_lift(_ buf: RustBuffer) throws -> ToDeviceEventType {
    return try FfiConverterTypeToDeviceEventType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeToDeviceEventType_lower(_ value: ToDeviceEventType) -> RustBuffer {
    return FfiConverterTypeToDeviceEventType.lower(value)
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias PrivOwnedStr = PrivateString

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrivOwnedStr: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrivOwnedStr {
        return try FfiConverterTypePrivateString.read(from: &buf)
    }

    public static func write(_ value: PrivOwnedStr, into buf: inout [UInt8]) {
        return FfiConverterTypePrivateString.write(value, into: &buf)
    }

    public static func lift(_ value: UInt64) throws -> PrivOwnedStr {
        return try FfiConverterTypePrivateString_lift(value)
    }

    public static func lower(_ value: PrivOwnedStr) -> UInt64 {
        return FfiConverterTypePrivateString_lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivOwnedStr_lift(_ value: UInt64) throws -> PrivOwnedStr {
    return try FfiConverterTypePrivOwnedStr.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivOwnedStr_lower(_ value: PrivOwnedStr) -> UInt64 {
    return FfiConverterTypePrivOwnedStr.lower(value)
}

/**
 * Construct a variant of the enum from a string.
 */
public func ephemeralRoomEventTypeFromString(s: String) -> EphemeralRoomEventType  {
    return try!  FfiConverterTypeEphemeralRoomEventType_lift(try! rustCall() {
    uniffi_ruma_events_fn_func_ephemeral_room_event_type_from_string(
        FfiConverterString.lower(s),$0
    )
})
}
/**
 * Construct a variant of the enum from a string.
 */
public func globalAccountDataEventTypeFromString(s: String) -> GlobalAccountDataEventType  {
    return try!  FfiConverterTypeGlobalAccountDataEventType_lift(try! rustCall() {
    uniffi_ruma_events_fn_func_global_account_data_event_type_from_string(
        FfiConverterString.lower(s),$0
    )
})
}
/**
 * Construct a variant of the enum from a string.
 */
public func messageLikeEventTypeFromString(s: String) -> MessageLikeEventType  {
    return try!  FfiConverterTypeMessageLikeEventType_lift(try! rustCall() {
    uniffi_ruma_events_fn_func_message_like_event_type_from_string(
        FfiConverterString.lower(s),$0
    )
})
}
/**
 * Construct a variant of the enum from a string.
 */
public func roomAccountDataEventTypeFromString(s: String) -> RoomAccountDataEventType  {
    return try!  FfiConverterTypeRoomAccountDataEventType_lift(try! rustCall() {
    uniffi_ruma_events_fn_func_room_account_data_event_type_from_string(
        FfiConverterString.lower(s),$0
    )
})
}
/**
 * Construct a variant of the enum from a string.
 */
public func stateEventTypeFromString(s: String) -> StateEventType  {
    return try!  FfiConverterTypeStateEventType_lift(try! rustCall() {
    uniffi_ruma_events_fn_func_state_event_type_from_string(
        FfiConverterString.lower(s),$0
    )
})
}
/**
 * Construct a variant of the enum from a string.
 */
public func timelineEventTypeFromString(s: String) -> TimelineEventType  {
    return try!  FfiConverterTypeTimelineEventType_lift(try! rustCall() {
    uniffi_ruma_events_fn_func_timeline_event_type_from_string(
        FfiConverterString.lower(s),$0
    )
})
}
/**
 * Construct a variant of the enum from a string.
 */
public func toDeviceEventTypeFromString(s: String) -> ToDeviceEventType  {
    return try!  FfiConverterTypeToDeviceEventType_lift(try! rustCall() {
    uniffi_ruma_events_fn_func_to_device_event_type_from_string(
        FfiConverterString.lower(s),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ruma_events_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_ruma_events_checksum_func_ephemeral_room_event_type_from_string() != 49031) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ruma_events_checksum_func_global_account_data_event_type_from_string() != 55409) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ruma_events_checksum_func_message_like_event_type_from_string() != 19374) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ruma_events_checksum_func_room_account_data_event_type_from_string() != 19617) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ruma_events_checksum_func_state_event_type_from_string() != 7090) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ruma_events_checksum_func_timeline_event_type_from_string() != 64429) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ruma_events_checksum_func_to_device_event_type_from_string() != 65088) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureRumaEventsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all