// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, RustBuffer, RustBuffer *_Nonnull);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

void ffi_matrix_sdk_ffi_91ce_StoppableSpawn_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void _uniffi_matrix_sdk_ffi_impl_StoppableSpawn_cancel_d04(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_StoppableSpawn_is_cancelled_c93c(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_SlidingSyncViewBuilder_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_SlidingSyncViewBuilder_new(
      
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_SlidingSyncViewBuilder_sync_mode(
      void*_Nonnull ptr,RustBuffer mode,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_SlidingSyncViewBuilder_required_state(
      void*_Nonnull ptr,RustBuffer required_state,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_SlidingSyncViewBuilder_build(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_SlidingSyncViewBuilder_add_range_13a3(
      void*_Nonnull ptr,uint32_t from,uint32_t to,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_SlidingSyncViewBuilder_batch_size_c33f(
      void*_Nonnull ptr,uint32_t batch_size,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_SlidingSyncViewBuilder_name_8e7b(
      void*_Nonnull ptr,RustBuffer name,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_SlidingSyncViewBuilder_no_timeline_limit_e80e(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_SlidingSyncViewBuilder_reset_ranges_8b42(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_SlidingSyncViewBuilder_sort_7839(
      void*_Nonnull ptr,RustBuffer sort,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_SlidingSyncViewBuilder_timeline_limit_4fbd(
      void*_Nonnull ptr,uint32_t limit,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_SlidingSyncView_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_SlidingSyncView_observe_room_list(
      void*_Nonnull ptr,uint64_t observer,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_SlidingSyncView_observe_rooms_count(
      void*_Nonnull ptr,uint64_t observer,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_SlidingSyncView_observe_state(
      void*_Nonnull ptr,uint64_t observer,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_SlidingSyncView_observe_room_items(
      void*_Nonnull ptr,uint64_t observer,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_SlidingSyncView_current_rooms_list(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void _uniffi_matrix_sdk_ffi_impl_SlidingSyncView_add_range_3ff2(
      void*_Nonnull ptr,uint32_t start,uint32_t end,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_SlidingSyncView_current_room_count_7123(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void _uniffi_matrix_sdk_ffi_impl_SlidingSyncView_reset_ranges_81ac(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void _uniffi_matrix_sdk_ffi_impl_SlidingSyncView_set_range_28fb(
      void*_Nonnull ptr,uint32_t start,uint32_t end,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_SlidingSyncRoom_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_SlidingSyncRoom_full_room_4a0b(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_SlidingSyncRoom_has_unread_notifications_a72f(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_SlidingSyncRoom_is_dm_4d1(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_SlidingSyncRoom_is_initial_d79e(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_SlidingSyncRoom_is_loading_more_fe3(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_SlidingSyncRoom_latest_room_message_6b3d(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_SlidingSyncRoom_name_86ea(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_SlidingSyncRoom_room_id_9b5e(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_SlidingSyncRoom_unread_notifications_e3f5(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_SlidingSync_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_SlidingSync_set_observer(
      void*_Nonnull ptr,RustBuffer observer,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_SlidingSync_subscribe(
      void*_Nonnull ptr,RustBuffer room_id,RustBuffer settings,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_SlidingSync_unsubscribe(
      void*_Nonnull ptr,RustBuffer room_id,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_SlidingSync_get_view(
      void*_Nonnull ptr,RustBuffer name,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_SlidingSync_get_room(
      void*_Nonnull ptr,RustBuffer room_id,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_SlidingSync_get_rooms(
      void*_Nonnull ptr,RustBuffer room_ids,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_SlidingSync_sync_1c2d(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_ClientBuilder_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_ClientBuilder_new(
      
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_ClientBuilder_build(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_ClientBuilder_base_path_2a3d(
      void*_Nonnull ptr,RustBuffer path,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_ClientBuilder_homeserver_url_8c7b(
      void*_Nonnull ptr,RustBuffer url,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_ClientBuilder_server_name_6b00(
      void*_Nonnull ptr,RustBuffer server_name,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_ClientBuilder_user_agent_6787(
      void*_Nonnull ptr,RustBuffer user_agent,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_ClientBuilder_username_4d4a(
      void*_Nonnull ptr,RustBuffer username,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_SlidingSyncBuilder_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_SlidingSyncBuilder_homeserver(
      void*_Nonnull ptr,RustBuffer url,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_SlidingSyncBuilder_build(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_SlidingSyncBuilder_add_fullsync_view_fcaf(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_SlidingSyncBuilder_add_view_26c9(
      void*_Nonnull ptr,void*_Nonnull v,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_SlidingSyncBuilder_no_views_ad32(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_SlidingSyncBuilder_with_common_extensions_ea25(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_Client_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_Client_set_delegate(
      void*_Nonnull ptr,RustBuffer delegate,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_Client_login(
      void*_Nonnull ptr,RustBuffer username,RustBuffer password,RustBuffer initial_device_name,RustBuffer device_id,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_Client_restore_login(
      void*_Nonnull ptr,RustBuffer restore_token,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_Client_restore_token(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_Client_user_id(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_Client_display_name(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_Client_avatar_url(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_Client_device_id(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_Client_account_data(
      void*_Nonnull ptr,RustBuffer event_type,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_Client_set_account_data(
      void*_Nonnull ptr,RustBuffer event_type,RustBuffer content,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_Client_get_media_content(
      void*_Nonnull ptr,void*_Nonnull source,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_Client_get_media_thumbnail(
      void*_Nonnull ptr,void*_Nonnull source,uint64_t width,uint64_t height,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_Client_get_session_verification_controller(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_Client_full_sliding_sync(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_Client_logout(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_Client_set_pusher(
      void*_Nonnull ptr,RustBuffer pushkey,RustBuffer kind,RustBuffer app_id,RustBuffer app_display_name,RustBuffer device_display_name,RustBuffer profile_tag,RustBuffer lang,RustBuffer url,RustBuffer format,RustBuffer default_payload,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_Client_has_first_synced_a950(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_Client_homeserver_a948(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_Client_is_guest_c78e(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_Client_is_soft_logout_533b(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_Client_is_syncing_7300(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_Client_rooms_9015(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_Client_sliding_sync_dd01(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void _uniffi_matrix_sdk_ffi_impl_Client_start_sync_e626(
      void*_Nonnull ptr,RustBuffer timeline_limit,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_Room_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_Room_display_name(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_Room_member_avatar_url(
      void*_Nonnull ptr,RustBuffer user_id,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_Room_member_display_name(
      void*_Nonnull ptr,RustBuffer user_id,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_Room_add_timeline_listener(
      void*_Nonnull ptr,uint64_t listener,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_Room_paginate_backwards(
      void*_Nonnull ptr,uint16_t limit,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_Room_send(
      void*_Nonnull ptr,void*_Nonnull msg,RustBuffer txn_id,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_Room_send_reply(
      void*_Nonnull ptr,RustBuffer msg,RustBuffer in_reply_to_event_id,RustBuffer txn_id,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_Room_redact(
      void*_Nonnull ptr,RustBuffer event_id,RustBuffer reason,RustBuffer txn_id,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_Room_avatar_url_4d24(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_Room_id_9008(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_Room_is_direct_e3a4(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_Room_is_encrypted_112d(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_Room_is_public_cd9a(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_Room_is_space_ac7a(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_Room_is_tombstoned_acd3(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_Room_membership_4bda(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_Room_name_ec9(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void _uniffi_matrix_sdk_ffi_impl_Room_remove_timeline_7d85(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_Room_topic_389d(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_TimelineDiff_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_TimelineDiff_replace(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_TimelineDiff_insert_at(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_TimelineDiff_update_at(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_TimelineDiff_remove_at(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_TimelineDiff_move(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_TimelineDiff_push(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_TimelineDiff_change_fa90(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_TimelineItem_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_TimelineItem_as_event_29dc(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_TimelineItem_as_virtual_ed31(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_TimelineItem_fmt_debug_2488(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_EventTimelineItem_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_EventTimelineItem_reactions(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_impl_EventTimelineItem_content_2662(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_EventTimelineItem_event_id_e7d(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_EventTimelineItem_fmt_debug_52c6(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_EventTimelineItem_is_own_e917(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_EventTimelineItem_key_ffba(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_EventTimelineItem_origin_server_ts_c0eb(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_EventTimelineItem_raw_867(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_EventTimelineItem_sender_1cf5(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_Message_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_Message_msgtype(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_Message_body_fffa(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_Message_in_reply_to_7d3a(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_Message_is_edited_e61f(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_RoomMessageEventContent_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_MediaSource_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_MediaSource_url(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_AuthenticationService_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_AuthenticationService_new(
      RustBuffer base_path,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_AuthenticationService_configure_homeserver(
      void*_Nonnull ptr,RustBuffer server_name,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_AuthenticationService_login(
      void*_Nonnull ptr,RustBuffer username,RustBuffer password,RustBuffer initial_device_name,RustBuffer device_id,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_AuthenticationService_restore_with_access_token(
      void*_Nonnull ptr,RustBuffer token,RustBuffer device_id,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_AuthenticationService_homeserver_details_63d3(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_NotificationService_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull matrix_sdk_ffi_91ce_NotificationService_new(
      RustBuffer base_path,RustBuffer user_id,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer matrix_sdk_ffi_91ce_NotificationService_get_notification_item(
      void*_Nonnull ptr,RustBuffer room_id,RustBuffer event_id,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_SessionVerificationEmoji_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_SessionVerificationEmoji_description_c0e1(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_SessionVerificationEmoji_symbol_eb61(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_SessionVerificationController_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_SessionVerificationController_set_delegate(
      void*_Nonnull ptr,RustBuffer delegate,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_SessionVerificationController_request_verification(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_SessionVerificationController_approve_verification(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_SessionVerificationController_decline_verification(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void matrix_sdk_ffi_91ce_SessionVerificationController_cancel_verification(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_SessionVerificationController_is_verified_d4e8(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void _uniffi_matrix_sdk_ffi_object_free_HomeserverLoginDetails_2400(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_HomeserverLoginDetails_authentication_issuer_2e81(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_HomeserverLoginDetails_supports_password_login_6dfc(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_HomeserverLoginDetails_url_7eb5(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void _uniffi_matrix_sdk_ffi_object_free_TimelineItemContent_2b31(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_impl_TimelineItemContent_as_message_9a93(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_TimelineItemContent_is_redacted_message_4ff0(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void _uniffi_matrix_sdk_ffi_object_free_UnreadNotificationsCount_b323(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
int8_t _uniffi_matrix_sdk_ffi_impl_UnreadNotificationsCount_has_notifications_8e89(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
uint32_t _uniffi_matrix_sdk_ffi_impl_UnreadNotificationsCount_highlight_count_ea64(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
uint32_t _uniffi_matrix_sdk_ffi_impl_UnreadNotificationsCount_notification_count_b16c(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void _uniffi_matrix_sdk_ffi_object_free_VirtualTimelineItem_21e1(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_ClientDelegate_init_callback(
      ForeignCallback  _Nonnull callback_stub,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_SlidingSyncObserver_init_callback(
      ForeignCallback  _Nonnull callback_stub,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_SlidingSyncViewStateObserver_init_callback(
      ForeignCallback  _Nonnull callback_stub,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_SlidingSyncViewRoomListObserver_init_callback(
      ForeignCallback  _Nonnull callback_stub,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_SlidingSyncViewRoomsCountObserver_init_callback(
      ForeignCallback  _Nonnull callback_stub,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_SlidingSyncViewRoomItemsObserver_init_callback(
      ForeignCallback  _Nonnull callback_stub,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_TimelineListener_init_callback(
      ForeignCallback  _Nonnull callback_stub,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_SessionVerificationControllerDelegate_init_callback(
      ForeignCallback  _Nonnull callback_stub,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer _uniffi_matrix_sdk_ffi_gen_transaction_id_401c(
      
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_media_source_from_url_245(
      RustBuffer url,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull _uniffi_matrix_sdk_ffi_message_event_content_from_markdown_dc3(
      RustBuffer md,
    RustCallStatus *_Nonnull out_status
    );
void _uniffi_matrix_sdk_ffi_setup_tracing_89c1(
      RustBuffer configuration,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_matrix_sdk_ffi_91ce_rustbuffer_alloc(
      int32_t size,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_matrix_sdk_ffi_91ce_rustbuffer_from_bytes(
      ForeignBytes bytes,
    RustCallStatus *_Nonnull out_status
    );
void ffi_matrix_sdk_ffi_91ce_rustbuffer_free(
      RustBuffer buf,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_matrix_sdk_ffi_91ce_rustbuffer_reserve(
      RustBuffer buf,int32_t additional,
    RustCallStatus *_Nonnull out_status
    );
